FROM mcr.microsoft.com/dotnet/sdk:6.0-bullseye-slim AS build-env
WORKDIR /app

# Copy necessary files and restore as distinct layer
#COPY ./entities-api/entities-api.csproj ./
#RUN dotnet restore

# Copy everything else and build
COPY ./entities-api ./entities-api
COPY ./shared ./shared
RUN dotnet publish -c Release -o out ./entities-api/entities-api.csproj

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-bullseye-slim
COPY --from=build-env /app/out .

# Expose ports
EXPOSE 6002/tcp
ENV ASPNETCORE_URLS http://*:6002

# Start
ENTRYPOINT ["dotnet", "entities-api.dll"]
